### ISSUE TITLE
Some ERRORS while reproduce on Android

### ISSUE THREAD

**Issue by LeDinhThuc157** [SontranBK/nfc_mobile_app#2]
- Enable multidex for apps with over 64K methods
    + Làm theo hướng dẫn ở đây "https://developer.android.com/studio/build/multidex#mdex-gradle"
    +  Ta có thể làm như sau: Mở file build.gradle trong "nfc_mobile_app-main\android\app". Add "multiDexEnabled = true" và implementation("androidx.multidex:multidex:2.0.1") vào dưới như code
android {
    defaultConfig {
        ...
        minSdk = 15
        targetSdk = 28
        multiDexEnabled = true
    }
    ...
}
dependencies {
    implementation("androidx.multidex:multidex:2.0.1")
}

-  Error: ADB exited with exit code 1
   Performing Streamed Install
   INSTALL_FAILED_ABORTED: User rejected permissions
    + Turn on Install via USB in developer mode ( Bật cài đặt qua USB ở chế độ nhà phát triển)
    + Mở Command (Window + R sau đó gõ cmd) chạy các lệnh sau:
               flutter clean
               flutter pub
               flutter run

-Error: Cannot run with sound null safety, because the following dependencies don't support null safety: - package:flutter_barcode_scanner
       flutter run --no-sound-null-safety
-Your project requires a newer version of the Kotlin Gradle plugin. │ │ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then update E:\thuc\Tranning\nfc_mobile_app-main\android\build.gradle: │ │ ext.kotlin_version = '<latest-version>'
      + Trong file  build.gradle (android/gradle) ta thay sửa dòng ext.kotlin_version = '1.5.10' thành  ext.kotlin_version = '1.6.10'

-[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(ExecutionException, java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Nonnull field "projectId" is null., Cause: java.lang.IllegalStateException: Nonnull field "projectId" is null., Stacktrace: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Nonnull field "projectId" is null.
      + Đã giải quyết vấn đề này trong gradle: 3.0.0 đến 3.1.0
         buildscript {
    dependencies {
        classpath 'com.google.gms:google-services:3.1.0'
    }
}

**Comment by SontranBK** [comment]
If Error code is as follow, check out this page: [Error: ADB exited with exit code 1 Performing Streamed Install](https://stackoverflow.com/questions/57000915/error-adb-exited-with-exit-code-1-performing-streamed-install)

Then fix by doing:
Run in terminal

$ flutter clean
and then

$ flutter pub get
and then

$ flutter packages get
then

$ flutter run --no-sound-null-safety
